#!/bin/sh
### BEGIN INIT INFO
# Provides:          Timelapse-Daemon
# Required-Start:    udev $time $local_fs 
# Required-Stop:     udev $time $local_fs 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Timelapse photo service.
# Description:	     Service to take periodic timelapse image captures using raspistill.
### END INIT INFO

# Copyright 2014 Chris Collins
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
   
# This is an init script for a timelapse photography service.
# This file should be placed in /etc/init.d/timelapse-daemon
#
# Author: Chris Collins
#

NAME=Timelapse-Daemon
PIDFILE=/var/run/timelapse-daemon.pid
DAEMON=/usr/local/bin/timelapse.sh

. /lib/lsb/init-functions

case "$1" in
	start)
		# Check if the PID file exists and check the status of the process
		[ -e $PIDFILE ] && ps -p `cat $PIDFILE` > /dev/null 2>&1 && exit 5
		# Start the daemon.
		log_daemon_msg "Starting $NAME"
		# Start the daemon witht he help of start-stop-daemon
		#Log the message appropriately
		$DAEMON > /dev/null 2>&1 &
		echo $! >$PIDFILE
		log_end_msg 0
		;;
	stop)
		# Stop the daemon
		log_daemon_msg "Stopping $NAME"
		if [ -e $PIDFILE ]; then
			kill -9 `cat $PIDFILE`
			rm -rf $PIDFILE
		else
			log_daemon_msg "$NAME is not running"
			log_end_msg 0
		fi
		;;
	restart)
		# Restart the daemon
		$0 stop && sleep 2 && $0 start
		;;
	status)
		# Check the status of the process
		if [ -e $PIDFILE ]; then
			log_daemon_msg "$NAME is running"
			log_end_msg 0
		else
			log_daemon_msg "$NAME is not running"
			log_end_msg 0 
		fi
		;;
	reload)
		# Reload the processs Basically sending a signal to the daemon to reload it's configuration
		$0 stop && sleep 2 && $0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|status}"
		exit 2
		;;
esac

exit 0
